{% set name = "readme_renderer" %}
{% set version = "45.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 030a8fac74904f8fba11ad1bb6964e3f76e896dc7e5e71f16af190c9056696d1

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - nh3 >=0.2.14
    - comrak >=0.0.11
    - docutils >=0.21.2
    - pygments >=2.5.1
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - readme_renderer
  source_files:
    - README.rst
  commands:
    - python -m readme_renderer README.rst

about:
  home: https://github.com/pypa/readme_renderer
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: readme_renderer is a library for rendering "readme" descriptions for Warehouse

extra:
  recipe-maintainers:
    - beenje
