{% set name = "readme_renderer" %}
{% set version = "42.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d55489f83be4992fe4454939d1a051c33edbab778e82761d060c9fc6b308cd1

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - nh3 >=0.2.14
    - cmarkgfm >=0.8.0
    - docutils >=0.13.1
    - pygments >=2.5.1
    - python >=3.8

test:
  imports:
    - readme_renderer
  source_files:
    - README.rst
  commands:
    - python -m readme_renderer README.rst

about:
  home: https://github.com/pypa/readme_renderer
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: readme_renderer is a library for rendering "readme" descriptions for Warehouse

extra:
  recipe-maintainers:
    - beenje
