{% set name = "readme_renderer" %}
{% set version = "26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbe9db71defedd2428a1589cdc545f9bd98e59297449f69d721ef8f1cfced68d

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python
    - pip
  run:
    - bleach >=2.1.0
    - cmarkgfm >=0.2.0
    - docutils >=0.13.1
    - future
    - pygments
    - python
    - setuptools
    - six

test:
  imports:
    - readme_renderer
    - readme_renderer.integration

about:
  home: https://github.com/pypa/readme_renderer
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: readme_renderer is a library for rendering "readme" descriptions for Warehouse

extra:
  recipe-maintainers:
    - jjhelmus
