schema_version: 1

context:
  name: readme_renderer
  version: "46.0"

package:
  name: ${{ name|lower }}
  version: "${{ version }}"

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: af3e964914f6310a33ff67b72a4bdd940bed8d7c3bdecd2d14f40edf284bfe90

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - nh3 >=0.2.14
    - comrak >=0.0.13
    - docutils >=0.21.2
    - pygments >=2.5.1
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - readme_renderer
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - python -m readme_renderer README.rst
    files:
      source:
        - README.rst
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: readme_renderer is a library for rendering "readme" descriptions for Warehouse
  homepage: https://github.com/pypa/readme_renderer

extra:
  recipe-maintainers:
    - beenje
